# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150914174135 on 2015-09-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(upload_to='clinic/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Направление'),
        ),
    ]
